### ISSUE TITLE
AttributeError being raised when handling another exception in sdc11073.sdcdevice.httpserver

### ISSUE THREAD

**Issue by maximilianpilz** [Draegerwerk/sdc11073#143]
The following AttributeError might occur during handling of what is described in #142 .

>   ...
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "venv\lib\site-packages\sdc11073\sdcdevice\sdcdeviceimpl.py", line 97, in stopAll
    return self._handler.stopAll(closeAllConnections, sendSubscriptionEnd)
  File "venv\lib\site-packages\sdc11073\sdcdevice\sdc_handlers.py", line 333, in stopAll
    self._httpServerThread.stop(closeAllConnections)
  File "venv\lib\site-packages\sdc11073\sdcdevice\httpserver.py", line 278, in stop
    self.httpd.shutdown()
AttributeError: 'NoneType' object has no attribute 'shutdown'

Found in version 1.1.22

**Comment by a-kleinf** [comment]
consequential error of #142
