### ISSUE TITLE
bug: namespaces getting deleted from nsmap

### ISSUE THREAD

**Issue by maximilianpilz** [Draegerwerk/sdc11073#191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The following report

```
<?xml version='1.0' encoding='UTF-8'?>
<s12:Envelope xmlns:wse="http://schemas.xmlsoap.org/ws/2004/08/eventing"
              xmlns:wsa="http://www.w3.org/2005/08/addressing"
              xmlns:s12="http://www.w3.org/2003/05/soap-envelope"
              xmlns:msg="http://standards.ieee.org/downloads/11073/11073-10207-2017/message"
              xmlns:pm="http://standards.ieee.org/downloads/11073/11073-10207-2017/participant"
              xmlns:ext="http://standards.ieee.org/downloads/11073/11073-10207-2017/extension"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <s12:Header>
        <wsa:To s12:mustUnderstand="true">https://127.0.0.1:51341/</wsa:To>
        <wsa:Action s12:mustUnderstand="true">
            http://standards.ieee.org/downloads/11073/11073-20701-2018/StateEventService/EpisodicAlertReport
        </wsa:Action>
        <wsa:MessageID>urn:uuid:095ea71f-d5cb-4a6f-a12b-19a84933efef</wsa:MessageID>
        <ns0:MyClIdentifier xmlns:ns0="http.local.com" wsa:IsReferenceParameter="true">
            urn:uuid:75793341-2aa2-4a33-adfe-c158a0ad2982
        </ns0:MyClIdentifier>
    </s12:Header>
    <s12:Body>
        <msg:EpisodicAlertReport MdibVersion="10"
                                 SequenceId="urn:uuid:2d6bfcf5-a29c-42e4-99e3-99ce4a4e0233">
            <msg:ReportPart>
                <msg:AlertState xsi:type="pm:AlertSystemState" DescriptorVersion="0" StateVersion="7"
                                ActivationState="On" LastSelfCheck="1688025072995" SelfCheckCount="8"
                                PresentPhysiologicalAlarmConditions="" PresentTechnicalAlarmConditions=""
                                DescriptorHandle="ASYS0"/>
            </msg:ReportPart>
        </msg:EpisodicAlertReport>
    </s12:Body>
</s12:Envelope>
```

results in

```
Traceback (most recent call last):
  File "sdc11073\sdcclient\subscription.py", line 328, in onNotification
    self.notification = soapEnvelope
    ^^^^^^^^^^^^^^^^^
  File "sdc11073\observableproperties\observables.py", line 156, in __set__
    self._getInstanceData(obj).setValue(value)
  File "sdc11073\observableproperties\observables.py", line 90, in setValue
    self._callFunc(func)
  File "sdc11073\observableproperties\observables.py", line 99, in _callFunc
    func(self.value)
  File "sdc11073\sdcclient\sdcclientimpl.py", line 544, in _onAnyStateEventReport
    return self._onEpisodicAlertReport(soapenvelope)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "sdc11073\sdcclient\sdcclientimpl.py", line 615, in _onEpisodicAlertReport
    self.episodicAlertReport = report
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "sdc11073\observableproperties\observables.py", line 156, in __set__
    self._getInstanceData(obj).setValue(value)
  File "sdc11073\observableproperties\observables.py", line 90, in setValue
    self._callFunc(func)
  File "sdc11073\observableproperties\observables.py", line 99, in _callFunc
    func(self.value)
  File "sdc11073\mdib\clientmdib.py", line 491, in _onEpisodicAlertReport
    allAlertContainers = self._msgReader.readEpisodicAlertReport(reportNode)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "sdc11073\mdib\msgreader.py", line 206, in readEpisodicAlertReport
    sc = self.mkStateContainerFromNode(alert)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "sdc11073\mdib\msgreader.py", line 135, in mkStateContainerFromNode
    nodeType = namespaces.txt2QName(nodeType, node.nsmap)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "sdc11073\namespaces.py", line 140, in txt2QName
    raise KeyError('Cannot make QName for {}, prefix is not in nsmap: {}'.format(text, doc_nsmap.keys()))
KeyError: "Cannot make QName for pm:AlertSystemState, prefix is not in nsmap: dict_keys(['msg', 'xsi'])"
```

### Expected Behavior

No such error occurs for the given report.

### Python Version

3.11.4

### Operating system

"win32" and "linux"

### Sdc11073 Version

1.1.26

### Further Information

"reportNode = copy.deepcopy(reportNode)" in the "sdc11073.mdib.clientmdib" module drops the namespace that is needed, but missing.

### Participation

- [ ] I am willing to submit a pull request to fix this bug.

**Comment by deichmab-draeger** [comment]
in _onEpisodicAlertReport and others:
 the copy.deepcopy of the reportNode hast the side effect that the copy has no parent node, and this results in a loss of the namespace declarations of parent node. 
possible solution: transfer the complete namespace map of the original to the copy.

**Comment by leon1995** [comment]
relates to #232

**Comment by leon1995** [comment]
please respect the bug reported in #232
