### ISSUE TITLE
bug: ReferenceProvider stopped working

### ISSUE THREAD

**Issue by ldeichmann** [Draegerwerk/sdc11073#198]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The ReferenceProvider throws an Exception when trying to deliver a notification.

### Expected Behavior

Not that.

### Minimal Reproducible Example

https://github.com/ldeichmann/ri_11073_integration_test

### Python Version

3.10

### Operating system

github runner ubuntu-latest

### Sdc11073 Version

master (14ff758e176faabada52a7b3ba186a7efed9f7ef)

### Link to sdc11073 Logs

https://github.com/ldeichmann/ri_11073_integration_test/actions/runs/5504289708/jobs/10030360540

### Participation

- [ ] I am willing to submit a pull request to fix this bug.

**Comment by leon1995** [comment]
relevant log lines 6267-6272:
```
2023-07-10 05:09:57,665 - sdc.device.subscrMgr - ERROR - could not send notification report http://standards.ieee.org/downloads/11073/11073-20701-2018/StateEventService/EpisodicAlertReport, error Traceback (most recent call last):
  File "/home/runner/work/ri_11073_integration_test/ri_11073_integration_test/sdc11073_git/src/sdc11073/provider/subscriptionmgr_async.py", line 212, in _async_send_notification_report
    await subscription.async_send_notification_report(body_node, action)
  File "/home/runner/work/ri_11073_integration_test/ri_11073_integration_test/sdc11073_git/src/sdc11073/provider/subscriptionmgr_async.py", line 58, in async_send_notification_report
    await soap_client.async_post_message_to(self.notify_to_url.path, message,
AttributeError: 'SoapClient' object has no attribute 'async_post_message_to'
```

**Comment by leon1995** [comment]
the problem is that [SubscriptionsManagerReferenceParamAsync](https://github.com/Draegerwerk/sdc11073/blob/master/examples/ReferenceTest/reference_device.py#L98) is used in combination with [sync default components](https://github.com/Draegerwerk/sdc11073/blob/master/examples/ReferenceTest/reference_device.py#L104)
