### ISSUE TITLE
Bug: Provider tutorial not working

### ISSUE THREAD

**Issue by turban1988** [Draegerwerk/sdc11073#344]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am new to this project and I am trying to get the tutorial running.

I cloned the project and tried to run the tutorial code when I wanted to run the `provider.py` I got the following error message:

```
2024-02-16 14:09:55,004 - sdc.discover - INFO - UDP socket listens on 127.0.0.1:3702
My UUID is 72313cab-7352-51c9-8373-8b4031a66ec7
2024-02-16 14:09:55,095 - sdc.device.ExtendedProduct - INFO - init_operations for sco sco.mds0.
2024-02-16 14:09:55,096 - sdc.device.op_reg - INFO - register operation "ActivateOperation handle=actop.mds0_sco_0 code=CodedValue(196279, codingsystem="urn:oid:1.2.840.10004.1.1.1.0.0.1") operation-target=mds0"
2024-02-16 14:09:55,096 - sdc.device.op_reg - INFO - register operation "SetContextStateOperation handle=ensemble.mds0_sco0 code=CodedValue(1234567, codingsystem="urn:oid:1.2.840.10004.1.1.1.0.0.1") operation-target=EN.mds0"
2024-02-16 14:09:55,097 - sdc.device.ExtendedProduct - INFO - role handler AudioPauseProvider added operations to mdib: ActivateOperationDescriptor AP__ON, ActivateOperationDescriptor AP__CANCEL
2024-02-16 14:09:55,097 - sdc.device.op_reg - INFO - register operation "ActivateOperation handle=AP__ON code=CodedValue(128284, codingsystem="urn:oid:1.2.840.10004.1.1.1.0.0.1") operation-target=mds0"
2024-02-16 14:09:55,097 - sdc.device.op_reg - INFO - register operation "ActivateOperation handle=AP__CANCEL code=CodedValue(128285, codingsystem="urn:oid:1.2.840.10004.1.1.1.0.0.1") operation-target=mds0"
2024-02-16 14:09:55,097 - sdc.device.ExtendedProduct - INFO - sco sco.mds0: all operations have a handler.
2024-02-16 14:09:55,097 - sdc.device.ExtendedProduct - INFO - init_operations for sco sco.vmd0.
2024-02-16 14:09:55,098 - sdc.device.ExtendedProduct - INFO - sco sco.vmd0 has no operations in mdib.
2024-02-16 14:09:55,098 - sdc.device.ExtendedProduct - INFO - init_operations for sco sco.vmd1.mds0.
2024-02-16 14:09:55,098 - sdc.device.op_reg - INFO - register operation "ActivateOperation handle=actop.vmd1_sco_0 code=CodedValue(196279, codingsystem="urn:oid:1.2.840.10004.1.1.1.0.0.1") operation-target=mds0"
2024-02-16 14:09:55,098 - sdc.device.op_reg - INFO - register operation "SetValueOperation handle=numeric.ch0.vmd1_sco_0 code=CodedValue(196276, codingsystem="urn:oid:1.2.840.10004.1.1.1.0.0.1") operation-target=numeric.ch0.vmd1"
2024-02-16 14:09:55,098 - sdc.device.op_reg - INFO - register operation "SetStringOperation handle=enumstring.ch0.vmd1_sco_0 code=CodedValue(196277, codingsystem="urn:oid:1.2.840.10004.1.1.1.0.0.1") operation-target=enumstring.ch0.vmd1"
2024-02-16 14:09:55,099 - sdc.device.op_reg - INFO - register operation "SetStringOperation handle=string.ch0.vmd1_sco_0 code=CodedValue(196278, codingsystem="urn:oid:1.2.840.10004.1.1.1.0.0.1") operation-target=string.ch0.vmd1"
2024-02-16 14:09:55,099 - sdc.device.ExtendedProduct - INFO - sco sco.vmd1.mds0: all operations have a handler.
2024-02-16 14:09:55,099 - sdc.device - INFO - no PeriodicReportsHandler
2024-02-16 14:09:55,099 - sdc.device - INFO - starting services, addr = ['127.0.0.1']
2024-02-16 14:09:55,116 - sdc.device.httpsrv - INFO - starting http server on 0.0.0.0:57664
2024-02-16 14:09:55,116 - sdc.device - INFO - serving Services on 127.0.0.1:57664
Traceback (most recent call last):
  File "F:\sdc11073\tutorial\provider\provider.py", line 85, in <module>
    set_local_ensemble_context(my_mdib, "MyEnsemble")
  File "F:\sdc11073\tutorial\provider\provider.py", line 35, in set_local_ensemble_context
    with mdib.transaction_manager() as mgr:
AttributeError: 'ProviderMdib' object has no attribute 'transaction_manager'
```

What have I missed?

### Expected Behavior

The provider starts without an error and can interact with the `consumer.py`

### Python Version

Python 3.9.1

### Operating system

win32

### Sdc11073 Version

sdc11073-0.0.0

### Participation

- [ ] I am willing to submit a pull request to fix this bug.

**Comment by deichmab-draeger** [comment]
Was fixed in b81a57f63d9fc6c1f3163c9058aa5858e630c8d3, 2024-02-27
